apiVersion: v1
kind: Namespace
metadata:
  name: grocy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
  labels:
    app: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grocy-data
---
apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
  labels:
    app: grocy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: grocy
---
apiVersion: v1
kind: Service
metadata:
  name: grocy-nodeport
  namespace: grocy
  labels:
    app: grocy
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Grocy"
    gethomepage.dev/description: "Household Management"
    gethomepage.dev/group: "Local Apps"
    gethomepage.dev/icon: "grocy.svg"
    gethomepage.dev/href: "http://192.168.8.197:30881"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30881
    name: http
  selector:
    app: grocy
