---
# Development Environment Infrastructure Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-infrastructure
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/timholm/k8s-infrastructure.git
    targetRevision: main
    path: environments/dev/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
