---
# Immich Supporting Resources (Postgres, Redis, Service Aliases)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-infra
  namespace: argocd
  labels:
    component: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/timholm/k8s-infrastructure.git
    targetRevision: main
    path: base/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Immich Application (Helm Chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  labels:
    component: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: "*"
    helm:
      valuesObject:
        image:
          tag: release
        immich:
          persistence:
            library:
              existingClaim: immich-library
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
