---
# Production Environment Infrastructure Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infrastructure
  namespace: argocd
  labels:
    environment: prod
  annotations:
    # Require manual sync for production
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/timholm/k8s-infrastructure.git
    targetRevision: main
    path: environments/prod/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    # Production requires manual sync - no automated sync
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
