apiVersion: v1
kind: Pod
metadata:
  name: kaniko-homepage-discovery-build
  namespace: homepage
spec:
  restartPolicy: Never
  initContainers:
  - name: clone-repo
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone https://github.com/timholm/k8s-infrastructure.git /repo
      cp -r /repo/apps/homepage-discovery/* /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: repo
      mountPath: /repo
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=/workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/homepage-discovery:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
  - name: repo
    emptyDir: {}
