apiVersion: v1
kind: Service
metadata:
  name: immich-external
  namespace: immich
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: immich
  ports:
  - port: 2283
    targetPort: 2283
    nodePort: 30283
    protocol: TCP
