apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-postgres-init
  namespace: immich
data:
  init.sql: |
    -- Create postgres superuser role for Immich chart compatibility
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgres') THEN
        CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres';
      END IF;
    END
    $$;
    -- Grant permissions to postgres user
    GRANT ALL PRIVILEGES ON DATABASE immich TO postgres;
